### ISSUE TITLE
点击不起作用

### ISSUE THREAD

**Issue by mayneyao** [easyworld/PlayJumpJumpWithMouse#1]
点击之后，控制台有log
first 403 572
distance:11
first 414 575
distance:62

但是不会跳，图片也不更新。

**Comment by ZDHJ9EZW** [comment]
我也遇到了这个问题

**Comment by wotermelon** [comment]
@mayneyao @ZDHJ9EZW 我的是小米mix2，如果是小米手机，在USB调试下方有``USB调试（安全设置）``打开允许模拟点击

**Comment by wotermelon** [comment]
但是截图没有更新

**Comment by ZDHJ9EZW** [comment]
@wotermelon 我打开 usb 调试（安全模式）后可以正常使用了，感谢。
在 BackgroundImage4Panel.java 下还有有一个图片读取的路径也要改的，是不是这个问题？

**Comment by easyworld** [comment]
之前有个变量没有设置好，已修正 #2  @mayneyao @ZDHJ9EZW @wotermelon

**Comment by hxzqlh** [comment]
点击，手机上跳转不准确，会摔死。小米max，adb 是 mac os 版本，java 1.9.1

**Comment by easyworld** [comment]
@hxzqlh [https://github.com/easyworld/PlayJumpJumpWithMouse/blob/master/src/com/company/BackgroundImage4Panel.java#L82](https://github.com/easyworld/PlayJumpJumpWithMouse/blob/master/src/com/company/BackgroundImage4Panel.java#L82) 
改下这个参数试试

**Comment by lzdon** [comment]
截屏没有显示完整，需要resize？

**Comment by wotermelon** [comment]
@easyworld 不同手机参数设置不一样？``2.19``->``2.4``在mix2上可以，这个值怎么测出来的。。。

**Comment by easyworld** [comment]
@lzdon 只关注小人和盒子，边缘没有显示出来应该不影响。

**Comment by easyworld** [comment]
@wotermelon 随便输入，然后二分查找

**Comment by HaoweiCh** [comment]
图片不刷新

**Comment by easyworld** [comment]
@Chaaang 稍微等会，速度比较慢
