### ISSUE TITLE
截图显示有问题

### ISSUE THREAD

**Issue by fanyikoukouchi** [easyworld/PlayJumpJumpWithMouse#12]
在win10系统下截图显示不出来，运行出现白屏

**Comment by ZZKdev** [comment]
没有开USB调试模式，我也是这样

**Comment by JKAK47** [comment]
我的win7系统，手机honor8 开了USB 调试模式也是白屏

**Comment by wangzhiok** [comment]
截图有问题，生成s.png图片打不开，导致白屏，点击报空指针，而点击白屏手机也动了

**Comment by easyworld** [comment]
目前在标准输出中加入了adb错误提示，可以根据提示定位问题。个人感觉是adb没有连上手机。
