### ISSUE TITLE
截图失败

### ISSUE THREAD

**Issue by kuunnss** [easyworld/PlayJumpJumpWithMouse#21]
String[] args = new String[] { "bash", "-c", adbPath + " exec-out screencap -p > " + screenshotLocation };
小米3 用该命令截图出来的文件0kb，截图失败
设备连接正常
用自己截的图测试 模拟点击可用 
不知道 截图 是什么问题

**Comment by easyworld** [comment]
@kuunnss 可以用终端执行一下上述命令吗

**Comment by BytesZero** [comment]
@easyworld  在终端执行命令图片有大小但不显示
