### ISSUE TITLE
playJumpJumpWithMouse.jar怎么生成的

### ISSUE THREAD

**Issue by qingguoguo** [easyworld/PlayJumpJumpWithMouse#24]

**Comment by zhihuitang** [comment]
同问

**Comment by BytesZero** [comment]
在这里，已经生产好了，点击下面链接：
[https://github.com/easyworld/PlayJumpJumpWithMouse/releases](https://github.com/easyworld/PlayJumpJumpWithMouse/releases)

**Comment by jeffery812** [comment]
可以自己生成, 在target目录下面
```java
mvn install
```

**Comment by qingguoguo** [comment]
谢谢
