### ISSUE TITLE
希望可以建个群，大家一起讨论反馈问题

### ISSUE THREAD

**Issue by BytesZero** [easyworld/PlayJumpJumpWithMouse#25]

**Comment by jeffery812** [comment]
建群拉上我: tangggod

**Comment by BytesZero** [comment]
博主建吧，然后公布出来，这样有问题反馈及时。我现在是白屏，图片显示不出来的问题。

**Comment by zhihuitang** [comment]
playJumpJumpWithMouse.jar这个在哪里?需要自己生成吗?

**Comment by BytesZero** [comment]
博主回来了，建群拉人吧，最好微信群吧

**Comment by BytesZero** [comment]
@bambootang 刚好有几个问题需要请教

**Comment by BytesZero** [comment]
@easyworld  今晚建群吗？

**Comment by easyworld** [comment]
@yy1300326388 你微信多少

**Comment by BytesZero** [comment]
@easyworld  toponelan

**Comment by easyworld** [comment]
![750338201089354636](https://user-images.githubusercontent.com/8280291/34462587-11a1430a-ee82-11e7-9614-afcb7e251815.jpg)

需要的可以加群
