### ISSUE TITLE
全自动模式设置方便写详细点吗?

### ISSUE THREAD

**Issue by qingguoguo** [easyworld/PlayJumpJumpWithMouse#26]

**Comment by Linkaiup** [comment]
同问

**Comment by qingguoguo** [comment]
设置成功后没有提示?不知道成功没有

**Comment by Linkaiup** [comment]
看效果就知道成功了没啊

**Comment by qingguoguo** [comment]
不成功,怎么搞

**Comment by Linkaiup** [comment]
他的全自动模式不准

**Comment by Linkaiup** [comment]
没法成功

**Comment by qingguoguo** [comment]
@Linkaiup 你的设置步骤是怎样的

**Comment by bambootang** [comment]
最主要的是魔数要设置正确。675×1200的魔数为2.175，自己根据你手机的分辨率来设置即可。比如手机屏幕分辨率是1080×1920，那魔数就是2.175×675/1080＝1.359375，依次类推进行换算。

**Comment by qingguoguo** [comment]
@bambootang 现在步骤是打开小程序,开始游戏    执行命令 java -jar playJumpJumpWithMouse.jar -m 3
再执行java -jar playJumpJumpWithMouse.jar -a <your adb path>  界面是出现,并没有自动跳,先不说准不准确的问题  所以想问,这个设置模式  是如何设置的

**Comment by bambootang** [comment]
java -jar playJumpJumpWithMouse.jar -ayouradbpath -r1.359375 -m3

**Comment by Linkaiup** [comment]
你还需要去下载adb，网上查一下如何安装adb，然后得在它的目录下运行，-r是魔数，-s 是分辨率。

**Comment by bambootang** [comment]
adb环境 文档最后有下载

**Comment by qingguoguo** [comment]
必须有adba ,已经在手动模式玩过了

**Comment by ZhuoLun** [comment]
各位大佬  白屏咋办 unknown SOURCE

**Comment by bambootang** [comment]
@ZhuoLun 手机要开启开发者模式，怎么开启自行百度吧。不同手里不同的操作。

**Comment by qingguoguo** [comment]
![image](https://user-images.githubusercontent.com/19551474/34460877-c3698470-ee56-11e7-8b5d-7310cccb938e.png)

**Comment by qingguoguo** [comment]
@bambootang 看下我的截图

**Comment by bambootang** [comment]
@qingguoguo -a参数是必须要的，你缺了-a参数

**Comment by qingguoguo** [comment]
最主要的是魔数要设置正确。675×1200的魔数为2.175，自己根据你手机的分辨率来设置即可。比如手机屏幕分辨率是1080×1920，那魔数就是2.175×675/1080＝1.359375，依次类推进行换算。

我的手机屏幕分辨率是1080*2040  那魔数还是2.175×675/1080＝1.359375吗? @bambootang

**Comment by bambootang** [comment]
@qingguoguo 是的

**Comment by ZhuoLun** [comment]
![qq 20171231182658](https://user-images.githubusercontent.com/9474679/34460938-7b560616-ee58-11e7-80b1-454383d37cf9.jpg)

我确定开启了开发者模式。。。

**Comment by ZhuoLun** [comment]
@bambootang  可以电你吗 哈哈

**Comment by bambootang** [comment]
@ZhuoLun 应该是参数写法错了

**Comment by ZhuoLun** [comment]
>java -jar playJumpJumpWithMouse-0.0.2.jar -a "C:\platform-tools-latest-windows\platform-tools\adb.exe"

@bambootang   我直接这样也报错。




C:\platform-tools-latest-windows\platform-tools>java -jar playJumpJumpWithMouse-0.0.2.jar -a "C:\platform-tools-latest-windows\platform-tools\adb.exe"
error: closed
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$1.paintComponent(BackgroundImage4Panel.java:171)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)

**Comment by ZhuoLun** [comment]
我的模拟器一直就是白屏。。。 是不是jdk版本问题？ 我是1.8.x

**Comment by qingguoguo** [comment]
![image](https://user-images.githubusercontent.com/19551474/34461004-214620c8-ee5a-11e7-8a2f-570c92b3bbc4.png)

**Comment by bambootang** [comment]
@ZhuoLun 去掉双引号，上面有一个示例。试试行不行。

**Comment by qingguoguo** [comment]
![image](https://user-images.githubusercontent.com/19551474/34461017-414a3daa-ee5a-11e7-84c4-6e56763ce178.png)

**Comment by qingguoguo** [comment]
@bambootang 按照你前面说的改了

**Comment by ZhuoLun** [comment]
@bambootang 


>java -jar playJumpJumpWithMouse-0.0.2.jar -a C:\platform-tools-latest-windows\platform-tools\adb.exe
error: closed
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$1.paintComponent(BackgroundImage4Panel.java:171)
        at javax.swing.JComponent.paint(Unknown Source)



不行 是不是BUG？ 哈哈 我不懂java

**Comment by bambootang** [comment]
@qingguoguo 双引号去掉。

**Comment by bambootang** [comment]
我要吃饭去了，祝你们成功😱

**Comment by qingguoguo** [comment]
路径的双引号去掉了,还是一样的 @bambootang

**Comment by bambootang** [comment]
@qingguoguo 你要更新到最新版，你用的这版m3是半自动模式。所以，你要用鼠标点终点的中点。

**Comment by qingguoguo** [comment]
嗯是的,我改成m2了,可行,非常感谢 @bambootang

**Comment by ZhuoLun** [comment]
@qingguoguo  能帮我下不

**Comment by Lixing1993** [comment]
`D:\Downloads>java -jar playJumpJumpWithMouse-0.0.2.jar -a D:\Downloads\platform-tools\adb.exe -r1.359375 -m2
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.StartCenterFinder.findStartCenter(StartCenterFinder.java:95)
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$3.run(BackgroundImage4Panel.java:252)`

**Comment by Lixing1993** [comment]
D:\Downloads>java -jar playJumpJumpWithMouse-0.0.2.jar -a D:\Downloads\platform-tools\adb.exe -r1.359375 -m2
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.company.playJumpJumpWithMouse.StartCenterFinder.findStartCenter(StartCenterFinder.java:95)
        at com.company.playJumpJumpWithMouse.BackgroundImage4Panel$3.run(BackgroundImage4Panel.java:252)

**Comment by wangyuan0217** [comment]
> 最主要的是魔数要设置正确。675×1200的魔数为2.175，自己根据你手机的分辨率来设置即可。比如手机屏幕分辨率是1080×1920，那魔数就是2.175×675/1080＝1.359375，依次类推进行换算。

那小米mix2的模数呢？  2160x1080的分辨率手机    那就是2.175×675/2160？好像不是吧    我自己一个运行一个数字一个数字试的  大概是1.45 @bambootang
