### ISSUE TITLE
为什么输入命令一直显示Error: Unable to access jarfile playJumpJumpWithMouse.jar

### ISSUE THREAD

**Issue by Pyre3290** [easyworld/PlayJumpJumpWithMouse#28]
小白问一下为什么输入命令一直显示Error: Unable to access jarfile playJumpJumpWithMouse.jar

**Comment by BytesZero** [comment]
因为你 jar 的路径有问题吧

**Comment by lxgyxp** [comment]
因该是打jar有问题吧 我也是小白 您知道了可以告诉我 我也不会 T.T

**Comment by easyworld** [comment]
@Pyre3290 路径加上引号试试
