### ISSUE TITLE
希望把使用方法再讲解的详细点，谢谢

### ISSUE THREAD

**Issue by cjcj125125** [easyworld/PlayJumpJumpWithMouse#32]
我这边报错  .\playJumpJumpWithMouse.jar中没有主清单属性
 

求解

**Comment by cjcj125125** [comment]
之前用Android studio打jar包的，现在用idea 用mvn命令弄好了，自动跳一跳就是有点慢，有时候纯白色的需要手动，是么？

**Comment by bambootang** [comment]
自动跳一跳是会慢一些，因为要去计算它的中心点，需要时间。自动模式下，不是没有页面吗？你怎么在自动模式下看到纯白色的？

**Comment by chengxuzhang** [comment]
不知道为啥，跑起来就报错

**Comment by qingguoguo** [comment]
004jar包对分辨率比较高的手机还是不准确2040*1080的

**Comment by athosss** [comment]
java -jar playJumpJumpWithMouse-0.0.4.jar -m auto-mode -a "D:\platform-tools\adb.exe" 全自动跑不起来啊，我的命令有问题吗？

**Comment by athosss** [comment]
自动模式下面弹出来一个java程序界面框，手机界面和这个界面都没有变化，怎么知道程序是跑起来呢还有成绩呢？

**Comment by ZhuoLun** [comment]
@athosss  你不要自动不行了嘛。 半自动其实就挺好。 反正全自动识别不是特别好。 自己搞一下 一会就23千分还不够嘛。6666
