### ISSUE TITLE
找不到小人中心点

### ISSUE THREAD

**Issue by Aiome** [easyworld/PlayJumpJumpWithMouse#34]
firstPoint = [x=0,y=-1]
distance:364
firstPoint = [x=0,y=-1]
distance:372
firstPoint = [x=0,y=-1]
distance:376
first 121 360
firstPoint = [x=0,y=-1]
distance:314
firstPoint = [x=0,y=-1]
distance:281
firstPoint = [x=0,y=-1]

不知道是不是我的截图质量问题还是什么问题，能否说下找小人中心点的思路，怎么把图片转成数组的？

**Comment by easyworld** [comment]
目前小人中心点用的像素识别，部分手机会对屏幕颜色做调整，导致识别不准确。
