### ISSUE TITLE
去掉的-r问题  小米mix2无法跳到中心点

### ISSUE THREAD

**Issue by wangyuan0217** [easyworld/PlayJumpJumpWithMouse#35]
#26 中最后我有提到过之前有-r的时候的 魔数算法在mix2上出错的问题，那会我自己挨个试了，最后大概是1.45附近，现在取消了-r参数无法跳到中心了

**Comment by bambootang** [comment]
那你先用0.0.3版本吧，release里面有。0.0.4只改了这里，所以直接用0.0.3也一样的。

**Comment by bambootang** [comment]
@wangyuan0217 你是半自动模式吧？ 小米mix2的分辨率与默认分辨率比例不相同，所以你得设置-s参数。 你设置成-s450x900，应该就准了。
