### ISSUE TITLE
Error: Unable to access jarfile playJumpJumpWithMouse.jar

### ISSUE THREAD

**Issue by sologuy** [easyworld/PlayJumpJumpWithMouse#36]
输入命令后报错,怎么办呢(mac)
Error: Unable to access jarfile playJumpJumpWithMouse.jar

**Comment by IAMJ** [comment]
用 jar 包的绝对路径就可以了

**Comment by Kwanloyal** [comment]
你直接复制的吧 哈哈哈  看看文件名(手动滑稽)

**Comment by IAMJ** [comment]
@Kwanloyal 😂还有版本号的

**Comment by sologuy** [comment]
弹出来一个java程序 没有图像 就一个框框 用的imac

**Comment by easyworld** [comment]
看下adb能连上手机不？
