### ISSUE TITLE
号被封了。。。。

### ISSUE THREAD

**Issue by LIUPING789** [easyworld/PlayJumpJumpWithMouse#38]
玩了半个小时， 用的半自动。。。  号被封了。。。

**Comment by wuyibin** [comment]
不是吧！！

**Comment by LIUPING789** [comment]
是真的，836分。。。  实在不想点鼠标了。。。 adb 报空了。。。

**Comment by wuyibin** [comment]
你的是什么手机》

**Comment by kdgcwufei** [comment]
@KnightOneAdmin 你是怎么点击的 为什么我点击下鼠标就弹很远 具体怎么操作的

**Comment by zqljintu** [comment]
这个是如何被检测出来的，我很纳闷？？

**Comment by LIUPING789** [comment]
用得大妹(魅)子(族)啊     我刷了一会就没刷了。  adb 。。。挂了〜   然后 。。。。  就  。。。 进不去了

**Comment by bambootang** [comment]
@KnightOneAdmin 号......被封了？ 封了后是什么状态，不能再玩跳一跳了？

**Comment by justorez** [comment]
封号太扯了吧？分数不显示或者一直清零才对。
