### ISSUE TITLE
自动模式下放弃等待那个时间，可以跳的更快一点

### ISSUE THREAD

**Issue by beinimaliesi** [easyworld/PlayJumpJumpWithMouse#45]
自动模式下，每跳一次就会等待，可能是判断不了有加分的块，所以没个都等待，其实可以完全放弃加分的块，跳的快一点，刷分更快。

**Comment by bambootang** [comment]
@tuxianchao 
你设置-t 值为 0 就可以了。等待是有意义的，因为执行完后有一个动画时间。所以必须得等动画执行结束才行。所以不建议设置为0，至少1000以上。

**Comment by beinimaliesi** [comment]
我重新打包了源码，就是设为1000，快了一点，不错
