### ISSUE TITLE
任何模式下小米6跳跃都会有误差

### ISSUE THREAD

**Issue by Leinox-github** [easyworld/PlayJumpJumpWithMouse#46]
任何模式下小米6跳跃都会有误差，每次跳跃都会差一小段，半自动模式往前点一点距离就可以消除，而室友的vivo却不会，不知道是什么原因引起的，我用Auto.js运行自动脚本就没有问题。

**Comment by bambootang** [comment]
小米6要设置-s参数

**Comment by Leinox-github** [comment]
![image](https://user-images.githubusercontent.com/21684910/34485110-ca956da0-f003-11e7-97aa-4d75ce922981.png)
设置了-s之后也是会有误差，会不会是小米6的屏幕触摸延时呢？不知道怎么设置按压时间

**Comment by bambootang** [comment]
-m3 不需要设置-s ，-m3 是会有一点误差的，有时候跳不到中心点，保证不死就等于无限分了。但绝大多数时候是跳中心点的。如果Auto.js 自动能跳中心点，那就用Auto.js啦，哪个好用用哪个，只要能满足需求就行啦。毕竟只是一个小游戏😁。

**Comment by Leinox-github** [comment]
对啊，应该是绝大部分跳中心，但是我的小米6基本是10次才有一次跳中心，这才是问题的关键，我在想问题是出在哪里。

**Comment by ftgqzhengkai** [comment]
最关键 小米6为什么跳不到多少分就跳死了、、

**Comment by Leinox-github** [comment]
@ftgqzhengkai 你用半自动模式，每次往前点一下，就可以跳中心

**Comment by ftgqzhengkai** [comment]
@Leinox-github 嗯，用这个最多能跳多少分？多少会被屏蔽？
