### ISSUE TITLE
javax.imageio.IIOException: Can't read input file!的问题

### ISSUE THREAD

**Issue by ZeoZhang** [easyworld/PlayJumpJumpWithMouse#5]
解决了，这个问题一般是端口暂用了。
删掉你的QQ/360/电脑管家/手机助手就好了。

**Comment by easyworld** [comment]
一会我在readme里面提一下

**Comment by hxzqlh** [comment]
[较低版本的adb不支持 exec-out 命令，我的是1.0.39没问题](https://github.com/easyworld/PlayJumpJumpWithMouse/pull/8)，我的1.0.39 还是会出现这个问题。已修复，见：https://github.com/hxzqlh/PlayJumpJumpWithMouse/blob/6249122ca548950f8a84297fd29ed86d23708e6a/src/com/company/AdbCaller.java#L21
