### ISSUE TITLE
大家来说说微信可能以什么方式判断是否脚本？

### ISSUE THREAD

**Issue by Leaflv** [easyworld/PlayJumpJumpWithMouse#52]
RT

**Comment by Leaflv** [comment]
如果是按键时间的话应该很好破

**Comment by dev-zlcode** [comment]
如果是根据时间来判断端是否为外挂，就搞个随机数设置间隔时间，他就测不出来了。

**Comment by leiyun-studio** [comment]
手动模式间隔是不一样的，也同样被检测！我觉得应该是模拟点击事件，如果能做个机械手点击，相当于程序只用于截图换个计算应该是没问题的。

**Comment by duanhengde** [comment]
我猜测：每次都调到下一个的中心点，人手不可能这么牛逼。可能微信根据这个行为判读是外挂做到的，所以屏蔽了分数

**Comment by HaoweiCh** [comment]
@duanhengde 很多工具的并没有做到每次跳中心也会被清空分数啊

**Comment by duanhengde** [comment]
我擦，这我就猜不出来了
