### ISSUE TITLE
别人的运行错误？ 图片路径不对吗？& 顺便说下识别中心点的原理吧

### ISSUE THREAD

**Issue by yovenny** [easyworld/PlayJumpJumpWithMouse#53]
运行命令为：java -jar C:\Users\pc\Desktop\playJumpJumpWithMouse.jar -a "C:\Users\pc\Desktop\platform-tools\adb.exe"  -m 3 -o "C:\Users\pc\Desktop\s.png" 

![wechatimg3382](https://user-images.githubusercontent.com/8280857/34512824-b74ea184-f09f-11e7-8976-e3eb47614733.png)

**Comment by yovenny** [comment]
系统为 windows，我mac机输出路径没填都可以呀

**Comment by yovenny** [comment]
奇了怪，讲道理是可以的呀

  if (commandLine.getOptionValue('o') != null) {
                AdbCaller.setScreenshotLocation(commandLine.getOptionValue('o'));
                screenshotPath = commandLine.getOptionValue('o');
            } else {
                AdbCaller.setScreenshotLocation("s.png");
                screenshotPath = "s.png";
            }

**Comment by bambootang** [comment]
@yovenny 对方没有安装adb，或者adb路径不对。

**Comment by qingguoguo** [comment]
android studio如何 run这个项目?

**Comment by easyworld** [comment]
@qingguoguo import maven项目就行(注意，这个不是安卓工程)

**Comment by easyworld** [comment]
@yovenny 已修复
